---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 60m0s
  wait: true
  force: true
  prune: true
  path: ./manifest/production
  sourceRef:
    kind: GitRepository
    name: flux-system
