---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 5m0s
  url: https://github.com/tshm/dotfiles/k8s
  ref:
    branch: main
  secretRef:
    name: flux-system
  timeout: 20s
