# Session environment

env=QT_QPA_PLATFORMTHEME,qt6ct
env=XCURSOR_SIZE,26
env=XMODIFIERS,@im=fcitx
env=GLFW_IM_MODULE,ibus
env=DefaultIMModule,fcitx
env=OZONE_PLATFORM,wayland
env=QT_QPA_PLATFORM,wayland
env=XDG_SESSION_TYPE,wayland

# Input

xkb_rules_layout=us,jp
numlockon=1
tap_to_click=1
tap_and_drag=1
drag_lock=1
drag_tile_to_tile=1
trackpad_natural_scrolling=1
mouse_natural_scrolling=0
