apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ns.yaml
  #- ingressroute.yaml

generatorOptions:
  disableNameSuffixHash: true
#
# secretGenerator:
#   - files:
#       - .dockerconfigjson=.docker.config.json
#     name: regcred
#     namespace: apps
#     type: kubernetes.io/dockerconfigjson
# configMapGenerator:
#   - envs:
#       - .app.env
#     name: env
#     namespace: apps
#
# replacements:
#   - source:
#       fieldPath: data.HOSTNAME_APP
#       kind: ConfigMap
#       name: env
#       version: v1
#   - source:
#       fieldPath: data.DOMAIN_APP
#       kind: ConfigMap
#       name: env
#       version: v1
