apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ns.yaml
  - ingressroute.yaml

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: regcred
    type: kubernetes.io/dockerconfigjson
    namespace: apps
    files:
      - .dockerconfigjson=.docker.config.json

configMapGenerator:
  - name: env
    namespace: apps
    envs:
      - .app.env

vars:
  - name: HOSTNAME_APP
    fieldref:
      fieldpath: data.HOSTNAME_APP
    objref:
      apiVersion: v1
      kind: ConfigMap
      name: env
  - name: DOMAIN_APP
    fieldref:
      fieldpath: data.DOMAIN_APP
    objref:
      apiVersion: v1
      kind: ConfigMap
      name: env
