apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: logging
  labels:
    k8s-app: fluent-bit
data:
  # Configuration files: server, input, filters and output
  # ======================================================
  fluent-bit.conf: |
    [SERVICE]
      Flush         1
      Log_Level     info
      Daemon        off
      Parsers_File  parsers.conf
      HTTP_Server   On
      HTTP_Listen   0.0.0.0
      HTTP_Port     2020

    @INCLUDE nodeexporter.conf
    @INCLUDE input-kubernetes.conf
    @INCLUDE filter-kubernetes.conf
    @INCLUDE output-loki.conf

  nodeexporter.conf: |
    [INPUT]
      name            node_exporter_metrics
      tag             node_metrics
      scrape_interval 5
    [OUTPUT]
      name                prometheus_exporter
      match               node_metrics
      port                3031

  input-kubernetes.conf: |
    [INPUT]
      Name              tail
      Tag               kube.*
      Path              /var/log/containers/*.log
      Parser            cri
      DB                /var/log/flb_kube.db
      Mem_Buf_Limit     15MB
      Refresh_Interval  10

  filter-kubernetes.conf: |
    [FILTER]
      Name                kubernetes
      Match               kube.*
      Kube_URL            https://kubernetes.default.svc:443
      Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
      Kube_Tag_Prefix     kube.var.log.containers.
      Merge_Log           On
      Merge_Log_Key       log
      K8S-Logging.Parser  On
      K8S-Logging.Exclude Off

  output-loki.conf: |
    # [OUTPUT]
    #   Name    stdout
    #   Match   *
    # [OUTPUT]
    #   Name          forward
    #   Match         *
    #   Host          ${LOGGING_HOST}
    #   Port          ${LOGGING_PORT}
    [OUTPUT]
      name                   loki
      match                  *
      host                   loki
      port                   3100
      labels                 context=app
      auto_kubernetes_labels on

  parsers.conf: |
    [PARSER]
      Name        cri
      Format      regex
      Regex       ^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<logtag>[^ ]*) (?<message>.*)$
      Time_Key    time
      Time_Format %Y-%m-%dT%H:%M:%S.%L%z
    [PARSER]
      Name        json
      Format      json
      Time_Key    time
      Time_Format %d/%b/%Y:%H:%M:%S %z
