apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: logging

resources:
  - namespace.yaml
  - grafana.yaml
  - loki.yaml
  - loki-configmap.yaml
  - prometheus.yaml
  - prometheus-configmap.yaml
  - fluent-bit-ds.yaml
  - fluent-bit-configmap.yaml

generatorOptions:
  disableNameSuffixHash: true
