apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: logging
  labels:
    k8s-app: prometheus
data:
  prometheus.yaml: |
    global:
      scrape_interval: 15s

    scrape_configs:
    - job_name: node
      static_configs:
      - targets: ['localhost:9100','fluent-bit:3031']
