# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cloudflared

resources:
  - namespace.yaml
  - cloudflared.yaml

secretGenerator:
  - name: cloudflared-token
    files:
      - token=.token.txt # This file should contain the token value

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: cloudflared-deployment
      spec:
        template:
          spec:
            containers:
            - name: cloudflared
              args:
              - --token
              - $(CF_TOKEN)
              env:
              - name: CF_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: cloudflared-token
                    key: token
