apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- cloudflared.yaml

generatorOptions:
  disableNameSuffixHash: true

# kubectl create secret generic tunnel-credentials --from-file=credentials.json=${HOME}/.cloudflared/${ID}.json
secretGenerator:
- files:
  - credentials.json=.cloudflared_credentials.json
  name: tunnel-credentials
  namespace: default
  type: generic

configMapGenerator:
- envs:
  - .app.env
  name: env
  namespace: apps

replacements:
- source:
    fieldPath: data.HOSTNAME_TUNNEL
    kind: ConfigMap
    name: env
    version: v1
- source:
    fieldPath: data.DOMAIN_TUNNEL
    kind: ConfigMap
    name: env
    version: v1
