# /etc/wsl.conf
[boot]
systemd=true
command=ip link set dev eth0 mtu 1280

[automount]
root = /
enabled = true
mountFsTab = false
options = "metadata"

[interop]
enabled = true
appendWindowsPath = true

[network]
generateResolvConf = false
