apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: authentik

generatorOptions:
  disableNameSuffixHash: true

resources:
  - ns.yaml

secretGenerator:
- name: authentik-secrets
  literals:
    - akadmin-password=$AUTHENTIK_SECRET
    - postgresql-password=$AUTHENTIK_PG_PASSWD
    - redis-password=$AUTHENTIK_REDIS_PASSWD

# secretGenerator:
#   - files:
#       - .dockerconfigjson=.docker.config.json
#     name: regcred
#     namespace: apps
#     type: kubernetes.io/dockerconfigjson

# configMapGenerator:
#   - name: authentik-values
#     namespace: authentik
#     files:
#       - values.yaml=.values.yaml

# replacements:
#   - source:
#       fieldPath: data.HOSTNAME_APP
#       kind: ConfigMap
#       name: env
#       version: v1
#   - source:
#       fieldPath: data.DOMAIN_APP
#       kind: ConfigMap
#       name: env
#       version: v1
