---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 60m0s
  wait: true
  force: true
  prune: true
  path: ./k8s/manifest/base/n8n
  sourceRef:
    kind: GitRepository
    name: flux-system
