apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: authentik

resources:
  - HelmRepository.yaml
  - HelmRelease.yaml

generatorOptions:
  disableNameSuffixHash: true

# secretGenerator:
#   - files:
#       - .dockerconfigjson=.docker.config.json
#     name: regcred
#     namespace: apps
#     type: kubernetes.io/dockerconfigjson

# configMapGenerator:
#   - name: authentik-values
#     namespace: authentik
#     files:
#       - values.yaml=.values.yaml

# replacements:
#   - source:
#       fieldPath: data.HOSTNAME_APP
#       kind: ConfigMap
#       name: env
#       version: v1
#   - source:
#       fieldPath: data.DOMAIN_APP
#       kind: ConfigMap
#       name: env
#       version: v1
