unset MAILCHECK
( which docker > /dev/null ) && {
  function dockerclean() {
    docker system df
    docker rm `docker ps -q`
    docker volume rm `docker volume ls -q -f dangling=true`
    docker system df
  }
}
(uname -a | grep Microsoft) && {
  alias scoopup="scoop update '*' && scoop cleanup '*' && scoop cache rm '*'"
  function e() {
    cmd.exe /c start $(wslpath -w $*)
  }
  function gvim() {
    args2=()
    for i in $*; do
      echo file: $i
      args2+="$(wslpath -aw $i) "
    done
    nvim-qt.exe $args2 &
  }
  function vim() {
    args2=()
    for i in $*; do
      echo file: $i
      args2+="$(wslpath -aw $i) "
    done
    nvim $args2
  }
}
[ -d /etc/apt ] && {
  function aptup() {
    sudo apt-get update
    sudo apt-get -y dist-upgrade
    sudo apt-get -y autoremove
    sudo apt-get -y cleanup
  }
}
[ -d /nix ] && {
  function nixup() {
    nix-channel --update
    nix-env -u
    nix-store --optimise
    nix-collect-garbage -d
  }
}
[ -d ~/.zinit ] && {
  function ziup() {
    zinit self-update
    zinit update
    zcompile ~/.zshrc
  }
}
