apiVersion: v1
kind: Service
metadata:
  name: loki
spec:
  selector:
    app: loki
  ports:
    - port: 3100
      targetPort: 3100
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
        - name: loki
          image: grafana/loki:2.4.2
          ports:
            - containerPort: 3100
          imagePullPolicy: Always
          volumeMounts:
            - name: logstorage
              mountPath: /tmp/loki
            - name: loki-config
              mountPath: /etc/loki/
      volumes:
        - name: logstorage
          hostPath:
            path: /home/loki
            type: DirectoryOrCreate
        - name: loki-config
          configMap:
            name: loki-config
