name: "build"
on:
  pull_request:
  push:

jobs:
  homemanager:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - "tshm@PN0093"
          - "tshm@minf"
          - "tshm@PD0056"
          - "tshm@x360"
          - "pi@spi"
    steps:
      - name: Checkout flake
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v16

      - uses: cachix/cachix-action@v14
        with:
          name: tshmcache
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Build ${{ matrix.package }}
        run: nix run home-manager/master -- build --flake .#${{ matrix.package }}

  nixos:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: ["x360", "minf"]
    steps:
      - name: Checkout flake
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v16

      - uses: cachix/cachix-action@v14
        with:
          name: tshmcache
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Build ${{ matrix.package }}
        run: nix-build --flake .#${{ matrix.package }}
