name: "Flake Checks"
on:
  push:
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Flake
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v16

      - name: nix flake check
        run: nix flake check
